USE crud01
GO

/* GENEROS */
DROP TABLE TBCADGEN
GO
/* ESTAO CIVIL */
DROP TABLE TBCADECV
GO
/* UF */
DROP TABLE TBCADUFE
GO

/* CADASTRO GERAL */

DROP TABLE TBCADUSU
GO

CREATE TABLE [dbo].[TBCADUFE]
(
	[CODUFE] CHAR(2) NOT NULL PRIMARY KEY, 
    [DSCUFE] VARCHAR(30) NOT NULL
)

CREATE TABLE [dbo].[TBCADGEN]
(
	[CODGEN] CHAR(1)    NOT NULL PRIMARY KEY, 
    [DSCGEN] VARCHAR(30) NOT NULL
)

CREATE TABLE [dbo].[TBCADECV]
(
	[CODECV] TINYINT     NOT NULL PRIMARY KEY, 
    [DSCECV] VARCHAR(30) NOT NULL
)


INSERT INTO TBCADUFE (CODUFE, DSCUFE) VALUES ('  ','')
INSERT INTO TBCADUFE (CODUFE, DSCUFE) VALUES ('SP','SAO PAULO')
INSERT INTO TBCADUFE (CODUFE, DSCUFE) VALUES ('MG','MINAS GERAIS')
INSERT INTO TBCADUFE (CODUFE, DSCUFE) VALUES ('RJ','RIO DE JANEIRO')
INSERT INTO TBCADGEN (CODGEN, DSCGEN) VALUES ('M','Masculino')
INSERT INTO TBCADGEN (CODGEN, DSCGEN) VALUES ('F','Feminino')
INSERT INTO TBCADGEN (CODGEN, DSCGEN) VALUES ('I','Indeterminado')
INSERT INTO TBCADECV (CODECV, DSCECV) VALUES (0,'N/D')
INSERT INTO TBCADECV (CODECV, DSCECV) VALUES (1,'SOLTEIRO')
INSERT INTO TBCADECV (CODECV, DSCECV) VALUES (2,'CASADO')

CREATE TABLE [dbo].[TBCADUSU](
	[CODUSU] [int] NOT NULL,
	[STAREC] [tinyint] NOT NULL,
	[DATCAD] [datetime] DEFAULT GETDATE() NOT NULL,
	[DATUPD] [datetime] NOT NULL DEFAULT GETDATE(),
	[TIPPES] [char](1) NOT NULL DEFAULT 'F',
	[CODPJU] [char](1) NOT NULL DEFAULT 'F',
	[NUMIRG] [char](20) NULL DEFAULT '',
	[CODCMF] [char](15) NOT NULL,
	[NOMUSU] [varchar](70) NOT NULL,
	[NOMMAE] [varchar](70) NOT NULL,
	[DATNAC] SMALLDATETIME NOT NULL,
	[CODATR] [int] NOT NULL DEFAULT 1,
	[ATRPPE] [bit] NOT NULL DEFAULT 0,
	[UFEEMI] [varchar](2) NOT NULL,
	[ORGEMI] [varchar](12) NOT NULL,
	[CODECV] [tinyint] NOT NULL DEFAULT 0,
 CONSTRAINT [PK_TBCADUSU] PRIMARY KEY CLUSTERED 
(
	[CODUSU] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


IF OBJECT_ID ( 'dbo.PRCADUSUINS', 'P' ) IS NOT NULL
    DROP PROCEDURE dbo.PRCADUSUINS;
GO

CREATE PROCEDURE [dbo].[PRCADUSUINS]
       (@STAREC tinyint = 1, 
        @TIPPES char(1) = 'F', 
        @NUMIRG char(20) = null, 
        @CODCMF char(15) = '', 
        @NOMUSU varchar(70), 
        @NOMMAE varchar(70) = '', 
        @DATNAC datetime = null, 
        @ULTACE datetime = null, 
        @CODATR int = 1, 
        @ATRPPE bit = 0, 
        @UFEEMI varchar(2) = '', 
        @ORGEMI varchar(12) = '', 
        @CODECV tinyint = 0, 
        @RETURN_VALUE int OUTPUT)
    AS
    SET NOCOUNT ON
	SET @RETURN_VALUE=0
	DECLARE @CODUSU INT
	DECLARE @CODPJU VARCHAR(1)='I'

	IF(@CODCMF IS NULL OR @CODCMF='')
	   SET @RETURN_VALUE=-1
    
	IF(@RETURN_VALUE=0)
		BEGIN
			IF(EXISTS(SELECT 1 FROM TBCADUSU (NOLOCK) WHERE CODATR=@CODATR AND CODCMF=@CODCMF))
				SET @RETURN_VALUE=-2
	    END


    IF(@RETURN_VALUE=0)
        BEGIN
			IF(LEN(@CODCMF)=11)
				SET @CODPJU = 'F'
  		    IF(LEN(@CODCMF)=14)
				SET @CODPJU = 'J'
		  SELECT @CODUSU= ISNULL(MAX(CODUSU),0) + 1 FROM TBCADUSU (NOLOCK)
		  INSERT INTO TBCADUSU (CODUSU, STAREC, TIPPES, CODPJU, NUMIRG, CODCMF, NOMUSU, NOMMAE, DATNAC, CODATR, ATRPPE, UFEEMI, ORGEMI, CODECV)
		                VALUES (@CODUSU, @STAREC, @TIPPES, @CODPJU, @NUMIRG, @CODCMF, @NOMUSU, @NOMMAE, @DATNAC, @CODATR, @ATRPPE, @UFEEMI, @ORGEMI, @CODECV)
            IF @@ERROR = 0
                BEGIN
                    SET @RETURN_VALUE = @CODUSU
                END
            ELSE
                BEGIN
                    SET @RETURN_VALUE = -3
                END
        END
    RETURN @RETURN_VALUE
GO

IF OBJECT_ID ( 'dbo.PRCADUSUUPD', 'P' ) IS NOT NULL
    DROP PROCEDURE dbo.PRCADUSUUPD;
GO

CREATE PROCEDURE [dbo].[PRCADUSUUPD]
       (@CODUSU INT,
	    @STAREC tinyint = 1, 
        @TIPPES char(1) = 'F', 
        @NUMIRG char(20) = null, 
        @CODCMF char(15) = '', 
        @NOMUSU varchar(70), 
        @NOMMAE varchar(70) = '', 
        @DATNAC datetime = null, 
        @CODATR int = 1, 
        @ATRPPE bit = 0, 
        @UFEEMI varchar(2) = '', 
        @ORGEMI varchar(12) = '', 
        @CODECV tinyint = 0, 
        @RETURN_VALUE int OUTPUT)
    AS
    SET NOCOUNT ON
	DECLARE @CODPJU VARCHAR(1)='I'
	SET @RETURN_VALUE=0;
    IF(@RETURN_VALUE=0)
        BEGIN
			IF(LEN(@CODCMF)=11)
				SET @CODPJU = 'F'
  		    IF(LEN(@CODCMF)=14)
				SET @CODPJU = 'J'

			 UPDATE TBCADUSU 
			    SET STAREC = @STAREC,
				    TIPPES = @TIPPES,
					CODPJU = @CODPJU,
					NUMIRG = @NUMIRG,
					CODCMF = @CODCMF,
					NOMUSU = UPPER(@NOMUSU),
					NOMMAE = UPPER(@NOMMAE),
					DATNAC = @DATNAC,
					CODATR = @CODATR,
					ATRPPE = @ATRPPE,
					UFEEMI = @UFEEMI,
					ORGEMI = @ORGEMI,
					CODECV = @CODECV,
					DATUPD = GETDATE()
              WHERE CODUSU = @CODUSU
            IF @@ERROR = 0
                BEGIN
                    SET @RETURN_VALUE = @CODUSU
                END
            ELSE
                BEGIN
                    SET @RETURN_VALUE = -1
                END
        END
    RETURN @RETURN_VALUE
GO


IF OBJECT_ID ( 'dbo.PRCADUSUSELALL', 'P' ) IS NOT NULL
    DROP PROCEDURE dbo.PRCADUSUSELALL;
GO


CREATE PROCEDURE PRCADUSUSELALL
(
   @CODATR INT =NULL,
   @NOMUSU VARCHAR(70)=NULL
)
AS
    SET NOCOUNT ON
	DECLARE @LIKENOMUSU VARCHAR(80)
	IF(@NOMUSU IS NULL OR @NOMUSU='')
	   SET @LIKENOMUSU = '%%'
	ELSE
	   SET @NOMUSU = '%' + @NOMUSU + '%'

	SELECT A.*, B.DSCECV, C.DSCGEN, D.DSCUFE 
	  FROM TBCADUSU (NOLOCK) A
     INNER JOIN TBCADECV (NOLOCK) B ON (B.CODECV = A.CODECV)
	 INNER JOIN TBCADGEN (NOLOCK) C ON (C.CODGEN = A.TIPPES)
	 INNER JOIN TBCADUFE (NOLOCK) D ON (D.CODUFE = A.UFEEMI)
    WHERE (@CODATR IS NULL OR A.CODATR=@CODATR)	  
	  AND NOMUSU LIKE @LIKENOMUSU

GO

IF OBJECT_ID ( 'dbo.PRCADUSUSEL', 'P' ) IS NOT NULL
    DROP PROCEDURE dbo.PRCADUSUSEL;
GO

CREATE PROCEDURE PRCADUSUSEL
(
   @CODUSU INT
)
AS
    SET NOCOUNT ON
	SELECT A.*
	  FROM TBCADUSU (NOLOCK) A
    WHERE CODUSU=@CODUSU

GO